name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build EXE
      run: pyinstaller main.py --onefile -w --icon=img/logo.ico

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: V2XrayMultiMapper.exe
        path: dist/main.exe
